"""Emit every numeric table of the paper into paper/draft/generated/*.tex.

Sources (hard rule 5):
  - results/stage4/backtests.csv, baseline_backtests.csv  (VaR audit, ES layer)
  - results/stage4/mcs_membership.csv                     (MCS membership)
  - results/stage4/regime_taurec_v2.csv                   (tau_rec)
  - docs/stage5_prescription.md                           (repair tables)

The prescription-derived tables are parsed from docs/stage5_prescription.md,
itself script-generated by harness/run_prescription.py from the matched repair
grid (results/stage4/repair_backtests_matched.csv etc.). Parsing the committed
canonical aggregation instead of re-implementing the success criterion here
avoids a second implementation that could drift from the frozen numbers; the
cross-checkable aggregates below are still re-computed from the CSVs and
asserted (see make_figures.py for the FZ0 re-computation asserts).

Every aggregate that also appears in paper/evidence_pack.md is asserted.
Run:  python paper/figures/make_tables.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))  # repo root (harness imports, v1.6)
from _shared import (ROOT, S4, BASE, MECH, NAME, TSFM, assert_pct, assert_val, check,
                     md_tables, tex_escape, write_tex)

ARM_ORDER = ["unrepaired", "F1", "F2", "F3", "F4", "H"]
HEAD_ORDER = ["chronos_2", "moirai_2_0", "lag_llama", "chronos_bolt", "timesfm_2_5"]


# ---------------------------------------------------------------- T1 taxonomy
def _headtype(ht: str) -> str:
    """Display form of the registry head-type identifier (v2.0 Phase-3
    P2-11: math-italic t, consistent with the prose's GARCH(1,1)-$t$)."""
    return {"parametric_student_t": r"parametric Student $t$"}.get(
        ht, tex_escape(ht.replace("_", " ")))


def _brk_tokens(s: str) -> str:
    """Hyphenated registry tokens get break points so the RaggedRight
    columns can wrap them (v2.0 Phase-3 P2-11 hyphenation fix)."""
    return tex_escape(str(s)).replace("-", r"-\allowbreak ")


def t_head_taxonomy():
    reg = yaml.safe_load((ROOT / "harness/registry.yaml").read_text())
    man = yaml.safe_load((S4 / "run_manifest.yaml").read_text())
    rows = []
    for m in TSFM:
        r, mm = reg[m], man["models"][m]
        cut = mm.get("pretraining_cutoff") or r["pretraining_cutoff"]
        import re
        tok = re.search(r"(?:upper bound|calendar cutoff)\s+(\d{4}-\d{2}(?:-\d{2})?)",
                        r["pretraining_cutoff"]).group(1)
        disclosed = "disclosed" if "DISCLOSED" in r["pretraining_cutoff"] else "upper bound"
        repo_brk = tex_escape(r["hf_repo"]).replace("/", r"/\allowbreak ") \
                                           .replace("-", r"-\allowbreak ")
        rows.append((NAME[m],
                     r"\texttt{" + repo_brk + r"}\newline @\,\texttt{"
                     + mm["hf_revision"][:7] + "}",
                     _headtype(mm["head_type"]),
                     _brk_tokens(mm["native_tail_behavior"]),
                     f"{tok} ({disclosed})"))
    # mechanism sub-panel rows (12-asset subset; registry-only source — the
    # stage-4 manifest predates the sub-panel by design)
    import re as _re
    mrows = []
    for m in MECH:
        r = reg[m]
        tok = _re.search(r"(?:upper bound|calendar cutoff)\s+(\d{4}-\d{2}(?:-\d{2})?)",
                         r["pretraining_cutoff"]).group(1)
        repo_brk = tex_escape(r["hf_repo"]).replace("/", r"/\allowbreak ") \
                                           .replace("-", r"-\allowbreak ")
        native = str(r["native_tail_behavior"]).split("#")[0].strip()
        mrows.append((NAME[m],
                      r"\texttt{" + repo_brk + r"}\newline @\,\texttt{"
                      + r["hf_revision"][:7] + "}",
                      _headtype(r["head_type"]),
                      _brk_tokens(native),
                      f"{tok} (upper bound)"))
    body = [
        r"\begin{table}[tbp]",
        r"\centering",
        r"\caption{The audited TSFM heads: pinned revision, output-head type, native",
        r"deep-tail behavior on a direct probe of the official implementation at",
        r"$\alpha\in\{1\%,2.5\%,5\%\}$, and the registered pretraining data cutoff",
        r"(calendar upper bound unless the vendor discloses one). Head type and native",
        r"behavior are interface facts frozen before any backtest was run. The five",
        r"core heads (upper block) run on the full 32-asset panel; the two mechanism",
        r"sub-panel heads (lower block) run on the 12-asset cross-category subset.}",
        r"\label{tab:heads}",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{\smallskipamount}",   # author layout fix (D3), fused 2026-07-17
        r"\begin{tabular}{@{}>{\RaggedRight}p{0.115\textwidth}>{\RaggedRight}p{0.30\textwidth}"
        r">{\RaggedRight}p{0.135\textwidth}>{\RaggedRight}p{0.175\textwidth}"
        r">{\RaggedRight}p{0.165\textwidth}@{}}",
        r"\toprule",
        r"model & repository @ revision & head type & native deep tail & cutoff \\",
        r"\midrule",
    ]
    for r in rows:
        body.append(" & ".join(r) + r" \\")
    body.append(r"\midrule")
    for r in mrows:
        body.append(" & ".join(r) + r" \\")
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write_tex("tab_heads.tex", "\n".join(body))


# ------------------------------------- T-decoding (v2.0 P0-5, Phase 2 block 4)
def t_decoding():
    """Chronos-base decoding-configuration sweep: 12-asset aggregate + the
    SPX real-window probe, from the tracked mechanism CSVs; asserted against
    the evidence-pack D14 values."""
    tk = pd.read_csv(ROOT / "results/mechanism/chronos_base_topk.csv")
    pr = pd.read_csv(ROOT / "results/mechanism/chronos_base_probes.csv")
    cfgs = [("topk50", r"top-$k=50$ (pinned vendor default)", "exact_cdf_topk50"),
            ("topk500", r"top-$k=500$", "exact_cdf_topk500"),
            ("untruncated", "untruncated", "exact_cdf_untruncated")]
    spx = pr[pr.asset == "spx"].set_index("method")
    ctx_q01 = float(spx.loc["realized_ctx", "q01"])
    bolt_q01 = float(spx.loc["chronos_bolt_stored", "q01"])
    want_hit = {"topk50": 32.34, "topk500": 7.59, "untruncated": 1.41}   # ep:347
    want_ucs = {"topk50": (0, 0, 0), "topk500": (0, 0, 0),
                "untruncated": (6, 10, 11)}                              # ep:348-349
    want_q01 = {"topk50": -0.093, "topk500": -1.488, "untruncated": -2.475}  # ep:351
    rows = []
    for key, label, meth in cfgs:
        d = tk[tk.config == key]
        h1 = 100.0 * d[d.alpha == 0.01].hit_rate.mean()
        assert_val(f"tab_decoding {key} mean hit", round(h1, 2), want_hit[key], tol=5e-3)
        ucs = [int((d[d.alpha == a].kupiec_p_mc >= 0.05).sum())
               for a in (0.01, 0.025, 0.05)]
        check(f"tab_decoding {key} UC pass", tuple(ucs) == want_ucs[key],
              f"{ucs} != {want_ucs[key]}")
        q01 = float(spx.loc[meth, "q01"])
        assert_val(f"tab_decoding {key} spx q01", round(q01, 3), want_q01[key], tol=5e-4)
        rows.append((label, f"{h1:.2f}\\%", f"{ucs[0]}/12", f"{ucs[1]}/12",
                     f"{ucs[2]}/12", f"${q01:.3f}$"))
    assert_val("tab_decoding spx ctx q01", round(ctx_q01, 3), -4.956, tol=5e-4)
    assert_val("tab_decoding spx bolt clamp q01", round(bolt_q01, 3), -1.120, tol=5e-4)
    body = [
        r"\begin{table}[tbp]",
        r"\centering",
        r"\caption{Chronos-base by decoding configuration on the 12-asset",
        r"mechanism sub-panel: mean violation rate of the nominal 1\% VaR,",
        r"MC-calibrated UC passes at the three tail levels, and the exact",
        r"categorical-CDF 1\% quantile on the SPX probe window (2021-03-31),",
        r"whose realized context 1\% quantile is $-4.956$ and whose stored",
        r"Chronos-Bolt clamp value is $-1.120$. One forward pass per window;",
        r"the top-$k=50$ row reproduces the delivered sampled E0 read",
        r"(32.34\% exact vs.\ 32.40\% sampled).}",
        r"\label{tab:decoding}",
        r"\small",
        # v2.0 Phase-4 micro-round: natural width exceeds the named build's
        # text block by ~74pt (colsep/font rungs arithmetically insufficient)
        # -> \resizebox to \textwidth; no-op-scale in the wider blinded layout.
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{@{}lccccc@{}}",
        r"\toprule",
        r"decoding & mean hit ($\alpha=1\%$) & UC 1\% & UC 2.5\% & UC 5\% & spx $q_{01}$ \\",
        r"\midrule",
    ]
    for r in rows:
        body.append(" & ".join(r) + r" \\")
    body += [r"\bottomrule", r"\end{tabular}}", r"\end{table}", ""]
    write_tex("tab_decoding.tex", "\n".join(body))


# ------------------------------------------------------------- T2 VaR audit
def t_var_audit():
    bt = pd.read_csv(S4 / "backtests.csv")
    bl = pd.read_csv(S4 / "baseline_backtests.csv")
    pas = lambda d: (d.kupiec_p_mc > 0.05).mean()

    frac = {}
    for m in TSFM:
        for e in ["e0", "e1", "e2", "e3"]:
            d = bt[(bt.forecaster == m) & (bt.erule == e)]
            frac[(m, e)] = pas(d) if len(d) else None
    for b in BASE:
        frac[(b, "param")] = pas(bl[bl.forecaster == b])

    # evidence-pack asserts (pack lines 101-116; E3 values re-anchored v2.1
    # Phase 3 to the empirical-mass store — machine-computed at re-anchor)
    assert_pct("chronos_2 E3", frac[("chronos_2", "e3")], 84)
    assert_pct("moirai_2_0 E3", frac[("moirai_2_0", "e3")], 92)
    assert_pct("timesfm_2_5 E3", frac[("timesfm_2_5", "e3")], 70)
    assert_pct("chronos_bolt E3", frac[("chronos_bolt", "e3")], 20)
    assert_pct("lag_llama E3", frac[("lag_llama", "e3")], 0)
    assert_pct("fhs param", frac[("fhs", "param")], 100)
    assert_pct("gjr_t param", frac[("gjr_t", "param")], 68)
    assert_pct("garch_t param", frac[("garch_t", "param")], 66)
    assert_pct("caviar param", frac[("caviar_sav", "param")], 95)
    assert_pct("hs500 param", frac[("hs500", "param")], 82)
    assert_pct("chronos_2 E1", frac[("chronos_2", "e1")], 2)
    assert_pct("timesfm E2", frac[("timesfm_2_5", "e2")], 70)

    fmt = lambda v: "---" if v is None else f"{round(v*100):d}\\%"
    body = [
        r"\begin{table}[tbp]",
        r"\centering",
        r"\caption{VaR audit: fraction of the 96 asset--tail cells (32 assets",
        r"$\times$ $\alpha\in\{1\%, 2.5\%, 5\%\}$) at which the",
        r"Monte-Carlo-calibrated Kupiec unconditional-coverage test does not",
        r"reject, by forecaster and extraction rule. `param' = econometric",
        r"baselines (no extraction rule). TimesFM-2.5 has no E0 forecast because",
        r"its official head rejects off-grid quantile levels. Higher indicates",
        r"fewer rejections; the rate is a descriptive summary of cell-level",
        r"decisions, not a jointly sized test.}",
        r"\label{tab:varaudit}",
        r"\small",
        r"\begin{tabular}{@{}lccccc@{}}",
        r"\toprule",
        r"forecaster & E0 & E1 & E2 & E3 & param \\",
        r"\midrule",
    ]
    for m in TSFM:
        cells = [fmt(frac[(m, e)]) for e in ["e0", "e1", "e2", "e3"]]
        body.append(f"{NAME[m]} & " + " & ".join(cells) + r" & --- \\")
    body.append(r"\midrule")
    for b in BASE:
        body.append(f"{NAME[b]} & --- & --- & --- & --- & {fmt(frac[(b,'param')])} \\\\")
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write_tex("tab_var_audit.tex", "\n".join(body))


def t_var_audit_alpha():
    """v1.5 item 1d (signer-directed): per-alpha Kupiec non-rejection rates at
    E3 plus the share of assets passing at all three levels simultaneously.
    Reference values recomputed independently by the signer; the asserts
    below must hit digit-for-digit (stop-and-report otherwise)."""
    bt = pd.read_csv(S4 / "backtests.csv")
    e3 = bt[bt.erule == "e3"]
    rows = {}
    for m in TSFM:
        d = e3[e3.forecaster == m]
        pooled = (d.kupiec_p_mc > 0.05).mean()
        per_a = [(d[d.alpha == a].kupiec_p_mc > 0.05).mean()
                 for a in (0.01, 0.025, 0.05)]
        all3 = (d.assign(ok=d.kupiec_p_mc > 0.05)
                 .groupby("asset").ok.sum() == 3).mean()
        rows[m] = (pooled, *per_a, all3)
    REF = {  # reference values (%, one decimal), v1.5 directive item 1d;
        # E3 rows re-anchored v2.1 Phase 3 (empirical-mass store, machine-
        # computed at re-anchor — never hand-typed)
        "chronos_bolt": (19.8, 34.4, 18.8, 6.2, 6.2),
        "chronos_2":    (84.4, 87.5, 78.1, 87.5, 75.0),
        "timesfm_2_5":  (69.8, 84.4, 68.8, 56.2, 40.6),
        "moirai_2_0":   (91.7, 90.6, 87.5, 96.9, 81.2),
        "lag_llama":    (0.0, 0.0, 0.0, 0.0, 0.0),
    }
    for m, want in REF.items():
        got = tuple(round(v * 100, 1) for v in rows[m])
        check(f"tab_var_audit_alpha {m}", got == want, f"{got} != {want}")

    fmt = lambda v: f"{v*100:.1f}\\%"
    body = [
        r"\begin{table}[tbp]",
        r"\centering",
        r"\caption{VaR audit by tail level, extraction rule E3: fraction of",
        r"the 32 assets per $\alpha$ at which the Monte-Carlo-calibrated",
        r"Kupiec unconditional-coverage test does not reject; the pooled",
        r"96-cell rate of Table~\ref{tab:varaudit}; and the fraction of",
        r"assets not rejected at all three levels simultaneously. Descriptive",
        r"summaries of cell-level decisions, not jointly sized tests.}",
        r"\label{tab:varauditalpha}",
        r"\small",
        r"\begin{tabular}{@{}lccccc@{}}",
        r"\toprule",
        r"forecaster & pooled & $\alpha=1\%$ & $\alpha=2.5\%$ & $\alpha=5\%$ & all three \\",
        r"\midrule",
    ]
    for m in TSFM:
        body.append(f"{NAME[m]} & " + " & ".join(fmt(v) for v in rows[m]) + r" \\")
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write_tex("tab_var_audit_alpha.tex", "\n".join(body))


def t_v15_robustness():
    """v1.5 items 10a/10b: decomposition-CI robustness + DM Newey-West
    sensitivity, from the script-generated v15 CSVs (zero new predictions)."""
    dec = pd.read_csv(S4 / "v15_decomp_robustness.csv")
    dm = pd.read_csv(S4 / "v15_dm_nw.csv")

    check("v15 loo_scale_min all > 0", bool((dec.loo_scale_min > 0).all()))
    check("v15 unclustered_scale_lo all > 0", bool((dec.unclustered_scale_lo > 0).all()))
    sig_f, sig_n = dm.p_frozen < 0.05, dm.p_nw < 0.05
    # v2.1.1 re-anchor (review #11 FAIL-1): counts from the v15 refresh under
    # the empirical-mass-E3 store (fidelity gate 4.44e-16 over 960 rows)
    check("v15 NW sig counts", int(sig_f.sum()) == 310 and int(sig_n.sum()) == 270,
          f"{int(sig_f.sum())}/{int(sig_n.sum())} != 310/270")
    check("v15 NW moved decisions", int((sig_f != sig_n).sum()) == 42,
          f"{int((sig_f != sig_n).sum())} != 42")
    ge = dm[dm.pair == "F1_vs_garch_evt"]
    f_f1 = ge[(ge.p_frozen < 0.05) & (ge.mean_diff < 0)]
    n_f1 = ge[(ge.p_nw < 0.05) & (ge.mean_diff < 0)]
    check("v15 F1-better cells == 2/2", len(f_f1) == 2 and len(n_f1) == 2,
          f"{len(f_f1)}/{len(n_f1)}")
    check("v15 F1-better sets identical",
          set(map(tuple, f_f1[["model", "asset"]].values))
          == set(map(tuple, n_f1[["model", "asset"]].values)))
    a1 = ge[ge.alpha == 0.01]
    check("v15 a1 frozen F1-better == 0", len(a1[(a1.p_frozen < 0.05) & (a1.mean_diff < 0)]) == 0)
    check("v15 a1 NW F1-better == 0", len(a1[(a1.p_nw < 0.05) & (a1.mean_diff < 0)]) == 0)

    fmt = lambda lo, hi: f"$[{lo:+.3f},\\,{hi:+.3f}]$"
    body = [
        r"\begin{table}[tbp]",
        r"\centering",
        r"\caption{Robustness of the location--scale decomposition intervals",
        r"($\alpha=1\%$, E3; same frozen per-asset paired FZ0 series as",
        r"Table~\ref{tab:decompci}, whose clustered six-class bootstrap uses",
        r"seed 20260717). LOO = range of the mean over the six deterministic",
        r"leave-one-asset-class-out subsets; boot = asset-level iid bootstrap",
        r"95\% intervals (B=2{,}000, seed 20260722). The clustered design of",
        r"Table~\ref{tab:decompci} is the headline specification.}",
        r"\label{tab:decomprobust}",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{@{}lcccc@{}}",
        r"\toprule",
        r"head & LOO scale & boot scale & LOO location & boot location \\",
        r"\midrule",
    ]
    for _, r in dec.iterrows():
        body.append(f"{NAME[r['head']]} & "
                    f"{fmt(r.loo_scale_min, r.loo_scale_max)} & "
                    f"{fmt(r.unclustered_scale_lo, r.unclustered_scale_hi)} & "
                    f"{fmt(r.loo_loc_min, r.loo_loc_max)} & "
                    f"{fmt(r.unclustered_loc_lo, r.unclustered_loc_hi)} \\\\")
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write_tex("tab_decomprobust.tex", "\n".join(body))

    rows = []
    for pair, pn in (("F1_vs_garch_evt", "F1 vs GARCH--EVT"),
                     ("F1_vs_F4", "F1 vs F4")):
        for a in (0.01, 0.025, 0.05):
            d = dm[(dm.pair == pair) & (dm.alpha == a)]
            sf, sn = d.p_frozen < 0.05, d.p_nw < 0.05
            # direction counts (v1.6 item C6): comparator = GARCH-EVT / F4;
            # mean_diff < 0 favors F1
            fc_f = int((sf & (d.mean_diff > 0)).sum())
            f1_f = int((sf & (d.mean_diff < 0)).sum())
            fc_n = int((sn & (d.mean_diff > 0)).sum())
            f1_n = int((sn & (d.mean_diff < 0)).sum())
            rows.append((pn, a, fc_f, f1_f, fc_n, f1_n,
                         int((sf != sn).sum())))
    # signer-verified exception sets (v1.6 C6): identical under both variances
    check("tab_dmnw GE exception count (frozen var)", sum(r[3] for r in rows if r[0].endswith("GARCH--EVT")) == 2)
    check("tab_dmnw GE exception count (NW var)", sum(r[5] for r in rows if r[0].endswith("GARCH--EVT")) == 2)
    # v2.1.1 (review #11): the F4-side pooled exception sets are no longer
    # equal across variances — six baseline / five NW, NW strictly nested
    f4p = dm[(dm.pair == "F1_vs_F4") & dm.alpha.isin([0.025, 0.05])]
    f4_f = f4p[(f4p.p_frozen < 0.05) & (f4p.mean_diff > 0)]
    f4_n = f4p[(f4p.p_nw < 0.05) & (f4p.mean_diff > 0)]
    kset = lambda x: set(map(tuple, x[["model", "asset", "alpha"]].values))
    check("tab_dmnw F4 exception counts (frozen/NW)",
          len(f4_f) == 6 and len(f4_n) == 5, f"{len(f4_f)}/{len(f4_n)} != 6/5")
    check("tab_dmnw F4 NW exceptions strictly nested in frozen",
          kset(f4_n) < kset(f4_f))
    body = [
        r"\begin{table}[tbp]",
        r"\centering",
        r"\caption{Diebold--Mariano variance sensitivity: of the 160",
        r"asset-level comparisons per pair and tail level, counts significant",
        r"at the 5\% test level under the baseline variance and under a",
        r"Newey--West (Bartlett) variance with automatic lag",
        r"$\lfloor 4(n/100)^{2/9}\rfloor$, split by direction",
        r"(favors the comparator / favors F1; the comparator is GARCH--EVT or",
        r"F4); `moved' counts decisions that change. Pooled levels = the 2.5\%",
        r"and 5\% tail levels; the two pooled-level F1-favoring exceptions",
        r"(F1 vs GARCH--EVT) are the same set under both variances; of the six",
        r"pooled-level F4-favoring exceptions (F1 vs F4) under the baseline",
        r"variance, five remain under Newey--West, a strict subset. The",
        r"baseline DM statistics were reproduced exactly (max deviation",
        # measured 4.44e-16 (v2.1.1 refresh); printed as the one-significant-
        # figure ceiling, same convention as the v1.5-era 8.9e-16 -> 9e-16
        r"$5\times10^{-16}$) before the variant was computed. The baseline",
        r"column retains the pre-frozen HLN-corrected $t(n-1)$ convention; the",
        r"Newey--West column reports uncorrected normal $p$-values.}",
        r"\label{tab:dmnw}",
        r"\small",
        r"\begin{tabular}{@{}lcccccc@{}}",
        r"\toprule",
        r" & & \multicolumn{2}{c}{baseline sig.} & \multicolumn{2}{c}{NW sig.} & \\",
        r"\cmidrule(lr){3-4}\cmidrule(lr){5-6}",
        r"pair & $\alpha$ & comp. & F1 & comp. & F1 & moved \\",
        r"\midrule",
    ]
    for pn, a, fc_f, f1_f, fc_n, f1_n, mv in rows:
        body.append(f"{pn} & {a*100:g}\\% & {fc_f} & {f1_f} & {fc_n} & {f1_n} & {mv} \\\\")
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write_tex("tab_dmnw.tex", "\n".join(body))



def t_esr():
    """v1.6 item C3 + v2.0 Phase-3 S-8/1i: strict-ESR non-rejection grid
    (96-cell shares) by forecaster and extraction rule, now including the E1
    misspecification-control column (esr_results.csv has always carried it);
    signer reference values asserted. E0 has no ES, hence no ESR column."""
    esr = pd.read_csv(S4 / "esr_results.csv")
    def rate(f, e):
        d = esr[(esr.forecaster == f) & (esr.erule == e)]
        return (d.esr_p > 0.05).mean() if len(d) else None
    # Reference values re-anchored v2.1 Phase 3 to the per-cell-SEEDED
    # engine's frozen output (sha deacbe03…, byte-identical across two full
    # runs; adjudication §8 ISSUE i) — machine-computed from esr_results.csv
    # at re-anchor time, never hand-typed.
    REF = {("chronos_bolt","e3"): 38.5, ("chronos_2","e3"): 41.7,
           ("lag_llama","e3"): 11.5, ("moirai_2_0","e3"): 85.4,
           ("timesfm_2_5","e3"): 82.3, ("chronos_bolt","e2"): 45.8,
           ("chronos_2","e2"): 34.4, ("lag_llama","e2"): 16.7,
           ("moirai_2_0","e2"): 49.0, ("timesfm_2_5","e2"): 80.2,
           ("garch_t","param"): 89.6, ("gjr_t","param"): 89.6,
           ("ewma94","param"): 8.3, ("fhs","param"): 78.1,
           ("hs250","param"): 28.1, ("hs500","param"): 43.8,
           ("chronos_bolt","e1"): 0.0, ("chronos_2","e1"): 0.0,
           ("lag_llama","e1"): 0.0, ("moirai_2_0","e1"): 6.2,
           ("timesfm_2_5","e1"): 2.1}
    for (f, e), want in REF.items():
        got = round(rate(f, e) * 100, 1)
        check(f"tab_esr {f}/{e}", got == want, f"{got} != {want}")
    body = [
        r"\begin{table}[tbp]",
        r"\centering",
        r"\caption{Strict ESR backtest: fraction of the 96 asset--tail cells",
        r"(32 assets $\times$ three $\alpha$ levels) at which the two-sided",
        r"asymptotic ESR test does not reject at the 5\% level, by forecaster",
        r"and extraction rule; E1 is the deliberately misspecified Gaussian",
        r"control. `param' = native econometric forecasts.",
        r"CAViaR-SAV forecasts VaR only and has no ES, hence no ESR cell;",
        r"E0 has no ES companion, hence no E0 column.",
        r"Each cell's test runs on that cell's own ES-valid day set (invalid",
        r"days removed; cells enter with at least 100 valid days and no",
        r"coverage gate), so ESR denominators differ from the FZ0/$Z_2$",
        r"validity sets stated in their tables.",
        r"The engine is the vendored \texttt{esback} strict ESR (version 1),",
        r"two-sided asymptotic $p$ with the bootstrap disabled ($B=0$) and",
        r"the point-estimation layer seeded per cell, so reported $p$-values",
        r"are exactly reproducible; unlike the UC/CC layer, this test",
        r"is not MC-calibrated at deep-tail sample sizes.",
        r"Descriptive summaries of cell-level decisions.}",
        r"\label{tab:esr}",
        r"\small",
        r"\begin{tabular}{@{}lcccc@{}}",
        r"\toprule",
        r"forecaster & E1 & E2 & E3 & param \\",
        r"\midrule",
    ]
    fmtp = lambda v: "---" if v is None else f"{v*100:.1f}\\%"
    for m in TSFM:
        body.append(f"{NAME[m]} & {fmtp(rate(m,'e1'))} & {fmtp(rate(m,'e2'))} "
                    f"& {fmtp(rate(m,'e3'))} & --- \\\\")
    body.append(r"\midrule")
    for b in BASE:
        v = rate(b, "param")
        body.append(f"{NAME[b]} & --- & --- & --- & {fmtp(v)} \\\\")
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write_tex("tab_esr.tex", "\n".join(body))


# ------------------------------------------- T3 ES with precision certificates
def t_es_precision():
    bt = pd.read_csv(S4 / "backtests.csv")
    bl = pd.read_csv(S4 / "baseline_backtests.csv")

    rows = []
    for f in TSFM + BASE:
        if f in TSFM:
            d = bt[(bt.forecaster == f) & (bt.erule == "e2") & (bt.alpha == 0.01)]
        else:
            d = bl[(bl.forecaster == f) & (bl.alpha == 0.01)]
        fz = d.fz0_mean.dropna()
        rows.append((f, fz.mean(), d.n_alpha.median(), int(fz.notna().sum()),
                     int((d.n_alpha < 10).sum())))

    got = {r[0]: r for r in rows}
    # evidence-pack asserts (pack lines 120-133)
    assert_val("chronos_2 FZ0", got["chronos_2"][1], 1.876)
    assert_val("gjr_t FZ0", got["gjr_t"][1], 1.799)
    assert_val("lag_llama FZ0", got["lag_llama"][1], 2.112)
    assert_val("moirai FZ0", got["moirai_2_0"][1], 1.884)
    assert_val("timesfm FZ0", got["timesfm_2_5"][1], 1.873)
    assert_val("bolt FZ0", got["chronos_bolt"][1], 1.890)
    assert_val("fhs FZ0", got["fhs"][1], 1.814)
    assert_val("garch_t FZ0", got["garch_t"][1], 1.800)
    assert_val("median n_alpha", got["chronos_2"][2], 26.4, tol=0.05)

    # v2.0 Phase-3 1h: CAViaR-SAV forecasts VaR only — no ES cell exists, so
    # the ES-side diagnostics (median n-alpha, fragile count) are dashes, not
    # numbers; printing the panel constant 26.4 next to valid-assets 0 was
    # internally contradictory.
    fzfmt = lambda v: "---" if pd.isna(v) else f"{v:.3f}"
    body = [
        r"\begin{table}[tbp]",
        r"\centering",
        # caption fused 2026-07-17: author terminal-draft wording (D3), with the
        # Pele attribution kept on the §4a F1 ruling ("adapted from")
        r"\caption{ES layer with finite-sample information diagnostics at $\alpha=1\%$, E2",
        r"extraction (TSFMs) and native parametric forecasts (baselines): mean FZ0",
        r"loss over assets (lower is better), median effective tail count",
        r"$n\alpha$, number of assets with a valid ES cell, and the number of",
        r"precision-fragile cells ($n\alpha<10$, the cell-level floor adapted",
        r"from \citet{pele2026precision}). The $(n\alpha)^{-1/2}$ scale is an",
        r"order-of-magnitude diagnostic, not a pairwise certificate; close FZ0 gaps",
        r"carry no substantive ranking claim.",
        r"`---': CAViaR-SAV forecasts VaR only and has no ES cell.}",
        r"\label{tab:es}",
        r"\small",
        r"\begin{tabular}{@{}lcccc@{}}",
        r"\toprule",
        r"forecaster & mean FZ0 & median $n\alpha$ & valid assets & fragile cells \\",
        r"\midrule",
    ]
    for f, fz, na, nv, nfrag in rows:
        sep = r"\midrule" if f == "garch_t" else None
        if sep and f == "garch_t":
            body.append(sep)
        if f == "caviar_sav":
            body.append(f"{NAME[f]} & --- & --- & {nv} & --- \\\\")
        else:
            body.append(f"{NAME[f]} & {fzfmt(fz)} & {na:.1f} & {nv} & {nfrag} \\\\")
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write_tex("tab_es_precision.tex", "\n".join(body))


# ------------------------------------------------------- T4 tau_rec (+censor)
def t_taurec():
    """v2.0 Phase-3 1j/S-3: medians at native half-day resolution (the old
    half-to-even rounding printed Moirai-2.0's 24.5 and FHS's 24.0 both as
    24), plus episode-bootstrap 95% CIs over the recovered episodes
    (B=10,000, per-cell seed 20260730 — same convention as
    harness/run_p3_stats §10, so doc and table match)."""
    tau = pd.read_csv(S4 / "regime_taurec_v2.csv")
    vix = tau[(tau["index"] == "vix") & (tau.window == 21)]
    layers = ([f"{m}:e3" for m in TSFM] + ["gjr_t", "fhs"])

    def cellstats(layer, a):
        s = vix[(vix.layer == layer) & (vix.alpha == a)]
        rec = s[s.ever_above & ~s.censored]
        if not len(rec):
            return "---", 0, int(s.censored.sum()), int((~s.ever_above).sum()), "---", "---"
        med = f"{rec.tau_rec.median():g}"
        iqr = (f"{rec.tau_rec.quantile(.25):.0f}--{rec.tau_rec.quantile(.75):.0f}")
        r = rec.tau_rec.to_numpy()
        rng = np.random.default_rng(20260730)
        boot = np.median(r[rng.integers(0, len(r), size=(10_000, len(r)))], axis=1)
        lo, hi = np.percentile(boot, [2.5, 97.5])
        ci = f"[{lo:.0f},{hi:.0f}]"
        return med, len(rec), int(s.censored.sum()), int((~s.ever_above).sum()), iqr, ci

    # evidence-pack asserts (medians at native half-day resolution; chronos_2
    # and lag_llama re-anchored v2.1 Phase 3 to the empirical-mass store —
    # machine-computed at re-anchor, never hand-typed)
    want = {"moirai_2_0:e3": ("24.5", 8, 1, 2), "fhs": ("24", 6, 1, 4),
            "chronos_2:e3": ("25.5", 8, 0, 3), "gjr_t": ("29", 9, 0, 2),
            "chronos_bolt:e3": ("30", 11, 0, 0), "timesfm_2_5:e3": ("31", 11, 0, 0),
            "lag_llama:e3": ("31", 7, 4, 0)}
    for lay, w in want.items():
        got = cellstats(lay, 0.05)[:4]
        check(f"tau_rec {lay}", got == w, f"{got} != pack {w}")

    body = [
        r"\begin{table}[tbp]",
        r"\centering",
        r"\caption{Event-time recovery after volatility-regime onsets: median",
        r"$\tau_{\mathrm{rec}}^{21}$ (trading days until the trailing-21-day pooled",
        r"violation rate first re-enters the calm-stratum null band from above) over",
        r"the eleven VIX-pool episodes, with an episode-bootstrap 95\% interval",
        r"for the median (recovered episodes resampled, $B=10{,}000$), the",
        r"interquartile range over the",
        r"recovered episodes, and recovered\,/\,censored\,/\,never-elevated",
        r"episode counts. An episode is censored when the rate is still above the band",
        r"at the end of the 60-day event window; never-elevated episodes (rate never",
        r"left the band) are excluded from the median. E3 extraction for TSFMs."
        r" Medians over an even number of recovered episodes land on half-days",
        r"and are shown at that resolution; IQR and interval endpoints are",
        r"rounded to whole days.}",
        r"\label{tab:taurec}",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{3.5pt}",
        r"\begin{tabular}{@{}lcccccccc@{}}",
        r"\toprule",
        r"& \multicolumn{4}{c}{$\alpha=5\%$} & \multicolumn{4}{c}{$\alpha=2.5\%$} \\",
        r"\cmidrule(lr){2-5}\cmidrule(lr){6-9}",
        r"layer & med. & 95\% CI & IQR & r/c/n & med. & 95\% CI & IQR & r/c/n \\",
        r"\midrule",
    ]
    for lay in layers:
        n = NAME[lay.split(":")[0]]
        m5, r5, c5, v5, q5, ci5 = cellstats(lay, 0.05)
        m25, r25, c25, v25, q25, ci25 = cellstats(lay, 0.025)
        if lay == "gjr_t":
            body.append(r"\midrule")
        body.append(f"{n} & {m5} & {ci5} & {q5} & {r5}/{c5}/{v5} & "
                    f"{m25} & {ci25} & {q25} & {r25}/{c25}/{v25} \\\\")
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write_tex("tab_taurec.tex", "\n".join(body))


# --------------------------------------- T5/T7/T8 prescription-derived tables
def t_prescription():
    text = (ROOT / "docs/stage5_prescription.md").read_text()
    tabs = md_tables(text)

    def tab(ctx_kw):
        for t in tabs:
            if ctx_kw.lower() in t["ctx"].lower():
                return t
        raise KeyError(ctx_kw)

    # success criterion
    sc = tab("Success criterion")
    idx = {h: i for i, h in enumerate(sc["headers"])}
    got_h = {r[0]: (r[idx["pass rate"]], r[idx["(b) frac"]], r[idx["joint"]])
             for r in sc["rows"] if r[idx["arm"]] == "H"}
    check("success-criterion H pass rates (c2/lag)",
          got_h["chronos_2"][0] == "69%" and got_h["lag_llama"][0] == "81%",
          f"{got_h}")

    body = [
        r"\begin{table}[tbp]",
        r"\centering",
        # v2.1 Phase 4 (P2-7): the float ran 1.97pt past the page; recovered
        # by caption-skip spacing (10pt -> 6pt, set BEFORE \caption), font
        # untouched per directive.
        r"\setlength{\abovecaptionskip}{6pt}",
        # caption fused 2026-07-17: author terminal-draft wording (D3)
        r"\caption{Pre-specified success criterion at $\alpha=1\%$, E3, matched",
        r"evaluation sample (out-of-sample day 501 onward, common day set):",
        r"(a) MC-UC+CC pass rate over assets $\geq$ FHS $-$ 10\,pp, i.e.",
        r"$\geq 68.1\%$; (b) per-asset FZ0 $\leq 1.05\times\min(\text{GJR-}t,",
        r"\text{FHS})$ on $\geq 2/3$ of all 32 assets (none fall below the",
        r"precision floor at the matched $n$). Assets without a valid repaired",
        r"ES cell (F4) count as failing condition (b); the denominator is always",
        r"the 32 assets. The matched median $n$ is 2139. The only arm that meets",
        r"the joint criterion on any head is H, and it does so on all five. The",
        r"final row applies the same two conditions to GARCH--EVT itself as a",
        r"reference self-check. Table~\ref{tab:decomp} decomposes the same",
        r"matched-sample FZ0 gaps into scale and location terms. Rows here and",
        r"in the other repair tables follow the repair-panel order (Chronos-2,",
        r"Moirai-2.0, Lag-Llama, Chronos-Bolt, TimesFM-2.5); the audit tables",
        r"of Sections~\ref{sec:var}--\ref{sec:regimes} use the panel order of",
        r"Table~\ref{tab:heads}.}",
        r"\label{tab:success}",
        r"\small",
        r"\begin{tabular}{@{}llcccc@{}}",
        r"\toprule",
        r"head & arm & pass rate & (a) & (b) frac & joint \\",
        r"\midrule",
    ]
    prev = None
    for r in sc["rows"]:
        head, arm = r[0], r[idx["arm"]]
        if prev and head != prev:
            body.append(r"\addlinespace")
        prev = head
        joint = r[idx["joint"]].replace("*", "")
        joint = r"\textbf{succeeds}" if joint == "SUCCEEDS" else "fails"
        aa = r[idx["(a)"]].replace("PASS", "pass")
        body.append(f"{NAME[head]} & {arm} & {r[idx['pass rate']]}".replace("%", r"\%")
                    + f" & {aa} & {r[idx['(b) frac']]} & {joint} \\\\")
    # v1.6 item D9: GARCH-EVT self-check row (machine-computed from the
    # frozen matched CSV via the criterion code path)
    from harness.run_prescription import coverage_pass, A as _A
    import numpy as _np
    rb_ = pd.read_csv(S4 / "repair_backtests_matched.csv")
    ge_ = rb_[(rb_.forecaster == "garch_evt") & (rb_.alpha == _A)].drop_duplicates("asset")
    fhs_ = rb_[(rb_.forecaster == "fhs") & (rb_.alpha == _A)].drop_duplicates("asset")
    gjr_ = rb_[(rb_.forecaster == "gjr_t") & (rb_.alpha == _A)].drop_duplicates("asset")
    ge_pr = coverage_pass(ge_)
    minref_ = pd.concat([gjr_.set_index("asset").fz0_mean,
                         fhs_.set_index("asset").fz0_mean], axis=1).min(axis=1)
    okb_ = []
    for asset_, fzv_ in ge_.set_index("asset").fz0_mean.items():
        ref_ = minref_.get(asset_, _np.nan)
        okb_.append(bool(_np.isfinite(fzv_) and _np.isfinite(ref_)
                         and (fzv_ - ref_ <= 0.05 if ref_ <= 0 else fzv_ <= 1.05 * ref_)))
    ge_bfrac = float(_np.mean(okb_))
    check("tab_success GE self-check", round(ge_pr * 100) == 72 and f"{ge_bfrac:.2f}" == "0.88",
          f"({ge_pr}, {ge_bfrac})")
    body.append(r"\midrule")
    body.append(f"GARCH--EVT & (self-check) & {round(ge_pr*100)}\\% & pass & {ge_bfrac:.2f} & (reference) \\\\")
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write_tex("tab_success.tex", "\n".join(body))

    # location/scale decomposition
    dc = tab("decomposition")
    di = {h: i for i, h in enumerate(dc["headers"])}
    check("decomposition lag scale +0.152",
          dc["rows"][2][di["scale term (F1−H)"]] == "+0.152",
          dc["rows"][2][di["scale term (F1−H)"]])
    body = [
        r"\begin{table}[tbp]",
        r"\centering",
        r"\caption{Location--scale decomposition of the repair gap: mean FZ0 at",
        r"$\alpha=1\%$, E3, matched sample. F1 = TSFM location + TSFM-IQR scale;",
        r"H = TSFM location + GARCH scale; GARCH--EVT = GARCH location + GARCH",
        r"scale. The scale term (F1$-$H) isolates the scale source at fixed TSFM",
        r"location; the location term (H$-$GARCH--EVT) isolates the location source",
        r"at fixed GARCH scale. Differences are computed before rounding.",
        r"Same sample, arms, and row order as Table~\ref{tab:success}.}",
        r"\label{tab:decomp}",
        r"\small",
        r"\begin{tabular}{@{}lccccc@{}}",
        r"\toprule",
        r"head & F1 & H & GARCH--EVT & scale (F1$-$H) & location (H$-$GE) \\",
        r"\midrule",
    ]
    for r in dc["rows"]:
        body.append(f"{NAME[r[0]]} & {r[1]} & {r[2]} & {r[3]} & {r[4]} & {r[5]} \\\\")
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write_tex("tab_decomp.tex", "\n".join(body))

    # repair matrix (appendix) — E2/E3 side by side, ALL FIVE heads.
    # v2.1 Phase-3 RESTATEMENT (review #10 P1-2): bare means over different
    # asset sets are no longer juxtaposed as comparable — every FZ0 mean
    # prints its n, cross-arm level comparisons move to a paired-difference
    # column (arm − unrepaired on their common finite assets), the three
    # missing-data classes are attributed separately in the caption, and the
    # F4 retained sets are published below the table (selection endogeneity
    # visible). A six-arm global intersection is FORBIDDEN (membership is
    # endogenous to F4's failure mode and flips signs/orderings; §7.2).
    # The doc-parsed cells are still string-asserted with the v2.0 formatter
    # first (fidelity gate), then re-rendered in the new geometry.
    hh = tab("Headline heads")
    hi = {h: i for i, h in enumerate(hh["headers"])}
    from harness.run_prescription import coverage_pass as _cp, A as _A2
    rb2 = pd.read_csv(S4 / "repair_backtests_matched.csv")

    def _sub(model, arm, erule):
        name = f"{model}+unrepaired" if arm == "unrepaired" else f"{model}+{arm}"
        return rb2[(rb2.forecaster == name) & (rb2.alpha == _A2)
                   & (rb2.erule == erule)].drop_duplicates("asset")

    def _cell(model, arm, erule):
        """(cov str, arm-specific mean FZ0 or None, finite-asset count)."""
        if arm in ("F1", "H") and erule == "e2":
            return "—", None, 0
        sub = _sub(model, arm, erule)
        if not len(sub):
            return "—", None, 0
        cov = f"{round(_cp(sub) * 100)}%"
        fz = sub.fz0_mean[np.isfinite(sub.fz0_mean)]
        return cov, float(fz.mean()), int(len(fz))

    for r in hh["rows"]:   # formatter fidelity gate vs the canonical doc
        head, arm = r[0], r[hi["arm"]]
        for er, ci, fi in (("e3", "cov E3", "FZ0 E3"), ("e2", "cov E2", "FZ0 E2")):
            cov, mean, k = _cell(head, arm, er)
            fzs = "—" if mean is None else (
                f"{mean:.3f}" + (f" (n={k})" if k < 32 else ""))
            assert cov == r[hi[ci]] and fzs == r[hi[fi]], (head, arm, er,
                (cov, fzs), (r[hi[ci]], r[hi[fi]]))

    def _delta(model, arm):
        """mean(FZ0_arm − FZ0_unrepaired) over common finite assets (E3)."""
        u = _sub(model, "unrepaired", "e3").set_index("asset").fz0_mean
        a = _sub(model, arm, "e3").set_index("asset").fz0_mean
        c = pd.concat([u, a], axis=1, keys=["u", "a"]).dropna()
        return float((c["a"] - c["u"]).mean()), int(len(c))

    doc_heads = list(dict.fromkeys(r[0] for r in hh["rows"]))
    all_heads = doc_heads + [h for h in HEAD_ORDER if h not in doc_heads]
    ARMS = [r[hi["arm"]] for r in hh["rows"] if r[0] == doc_heads[0]]
    body = [
        r"\begin{table}[tbp]",
        r"\centering",
        # v2.1 Phase 4 (flag 5): caption skip must be set BEFORE \caption
        r"\setlength{\abovecaptionskip}{4pt}",
        r"\caption{Repair matrix for all five heads at $\alpha=1\%$, matched",
        r"sample: coverage (fraction of assets passing MC UC+CC at 5\%), mean",
        r"FZ0 with its asset count $n$ in parentheses, and the paired",
        r"difference $\Delta$ = mean(FZ0$_{\mathrm{arm}}$ $-$",
        r"FZ0$_{\mathrm{unrepaired}}$) over the assets where both are finite",
        r"(common $n$ in parentheses; negative favors the arm), E3 and E2",
        r"extraction side by side. Cross-arm level comparisons should read",
        r"$\Delta$, not the bare means: the asset sets differ by arm in three",
        r"distinct ways. Unrepaired, F2, and F3 lose dgs2 and dgs30",
        r"($n{=}30$), where $\xi\ge1$ windows leave the E3 ES undefined on",
        r"more than 1\% of matched days, failing the 99\% ES-validity gate;",
        r"F1 and H replace the extraction tail, so their ES is valid on all",
        r"32 assets (and no E2 column applies); F4's additive shift breaks",
        r"$e<v$ on more than 1\% of days in every excluded cell, and its",
        r"retained assets --- listed below the table --- are endogenous to",
        r"that failure mode. No displayed cell is flagged by the",
        r"low-information screen at the matched $n$ (median 2139).}",
        r"\label{tab:repairmatrix}",
        r"\footnotesize",
        # v2.1 Phase 4 (flag 5): the restated 7-col geometry overflows the
        # named preprint text block by 20.9pt at the default \tabcolsep —
        # sizing-ladder rung 1 (colsep), font untouched. Vertically the float
        # (30 rows + caption + F4-note block) ran 86.8pt past the named page:
        # recovered by SPACING devices only — caption skip 10->6pt (set above,
        # before \caption), row leading 0.9 (data font untouched), group
        # \addlinespace at 1pt (comment re-aligned with the emitted value,
        # v2.1.1 review #11), and the auxiliary F4-note apparatus at
        # \scriptsize.
        r"\renewcommand{\arraystretch}{0.9}",
        r"\setlength{\tabcolsep}{3.5pt}",
        r"\begin{tabular}{@{}llccccc@{}}",
        r"\toprule",
        r"head & arm & cov.\ E3 & FZ0 E3 ($n$) & $\Delta$ vs unrep.\ ($n$)"
        r" & cov.\ E2 & FZ0 E2 ($n$) \\",
        r"\midrule",
    ]
    prev = None
    for head in all_heads:
        for arm in ARMS:
            if prev and head != prev:
                body.append(r"\addlinespace[1pt]")
            prev = head
            c3, m3, k3 = _cell(head, arm, "e3")
            c2, m2, k2 = _cell(head, arm, "e2")
            f3s = "---" if m3 is None else f"{m3:.3f} ({k3})"
            f2s = "---" if m2 is None else f"{m2:.3f} ({k2})"
            if arm == "unrepaired":
                ds = "---"
            else:
                dv, dk = _delta(head, arm)
                ds = f"${dv:+.3f}$ ({dk})"
            c3s = c3.replace("%", r"\%").replace("—", "---")
            c2s = c2.replace("%", r"\%").replace("—", "---")
            body.append(f"{NAME[head]} & {arm} & {c3s} & {f3s} & {ds} & "
                        f"{c2s} & {f2s} \\\\")
    f4_note = []
    for head in all_heads:
        kept = sorted(_sub(head, "F4", "e3")
                      .loc[lambda d: np.isfinite(d.fz0_mean), "asset"])
        f4_note.append(f"{NAME[head]} ({len(kept)}): "
                       + ", ".join(tex_escape(a) for a in kept))
    body += [r"\bottomrule", r"\end{tabular}",
             r"\par\vspace{1pt}",
             r"\begin{minipage}{\linewidth}\scriptsize",
             r"F4 retained assets (E3, $\alpha=1\%$): " + "; ".join(f4_note)
             + r". All other assets are excluded by the $e<v$ failure above;",
             r"the complement of each list is the excluded set.",
             r"\end{minipage}",
             r"\end{table}", ""]
    write_tex("tab_repairmatrix.tex", "\n".join(body))

    # F2 gamma robustness (appendix)
    gm = tab("gamma robustness")
    gi = {h: i for i, h in enumerate(gm["headers"])}
    body = [
        r"\begin{table}[tbp]",
        r"\centering",
        r"\caption{F2 (adaptive conformal) step-size robustness at $\alpha=1\%$,",
        r"E3, matched sample: coverage and mean FZ0 under $\gamma\in\{0.5\times,",
        r"1\times,2\times\}$ of the pre-specified scale $0.01\hat{s}$.}",
        r"\label{tab:gamma}",
        # v2.0 Phase-4 micro-round: \small width exceeds the named text block
        # by ~52pt; neither single rung suffices -> font + colsep combined.
        r"\footnotesize",
        r"\setlength{\tabcolsep}{3pt}",
        r"\begin{tabular}{@{}lcccccc@{}}",
        r"\toprule",
        r"head & cov.\ $0.5\times$ & cov.\ $1\times$ & cov.\ $2\times$ &"
        r" FZ0 $0.5\times$ & FZ0 $1\times$ & FZ0 $2\times$ \\",
        r"\midrule",
    ]
    for r in gm["rows"]:
        cells = [c.replace("%", r"\%") for c in r[1:7]]
        body.append(f"{NAME[r[0]]} & " + " & ".join(cells) + r" \\")
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write_tex("tab_gamma.tex", "\n".join(body))


# --------------------------------------------------------- T6 MCS membership
def t_mcs():
    """v2.0 Phase-3 1g: dual-level (10%/25%) membership per the registered
    protocol (proposal §3.4 "Hansen MCS(10%/25%)"); the 10% layer is gated
    against the delivered mcs_membership.csv by run_mcs_levels, and the same
    values are re-asserted here."""
    mc = pd.read_csv(S4 / "mcs_membership_levels.csv")
    e2 = mc[mc.erule.isin(["e2", "param"])]

    def rate(f, a, lv):
        d = e2[(e2.forecaster == f) & (e2.alpha == a) & (e2.level == lv)]
        return float(d.mcs_rate.iloc[0]) if len(d) else None

    assert_pct("lag_llama MCS a=5%", rate("lag_llama", 0.05, 0.10), 9)
    assert_pct("chronos_2 MCS a=5%", rate("chronos_2", 0.05, 0.10), 97)

    body = [
        r"\begin{table}[tbp]",
        r"\centering",
        r"\caption{Model Confidence Set membership rate (fraction of assets on",
        r"which the forecaster is in the MCS by FZ0 loss) at the two registered",
        r"levels, 10\% and 25\%, E2 extraction for",
        r"TSFMs, by $\alpha$. Higher = more often statistically indistinguishable",
        r"from the best; the 25\% level eliminates more aggressively, so its",
        r"rates bound the 10\% rates from below. `---': CAViaR-SAV forecasts",
        r"VaR only, so FZ0 loss is undefined.}",
        r"\label{tab:mcs}",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{@{}lcccccc@{}}",
        r"\toprule",
        r" & \multicolumn{3}{c}{10\% level} & \multicolumn{3}{c}{25\% level} \\",
        r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}",
        r"forecaster & $\alpha=1\%$ & $2.5\%$ & $5\%$ & $\alpha=1\%$ & $2.5\%$ & $5\%$ \\",
        r"\midrule",
    ]
    for f in TSFM + BASE:
        cells = []
        for lv in (0.10, 0.25):
            for a in (0.01, 0.025, 0.05):
                v = rate(f, a, lv)
                cells.append("---" if v is None else f"{round(v*100)}\\%")
        if f == "garch_t":
            body.append(r"\midrule")
        body.append(f"{NAME[f]} & " + " & ".join(cells) + r" \\")
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write_tex("tab_mcs.tex", "\n".join(body))


# ----------------------------------------- v2.0 Phase-3 new appendix tables
def t_z2():
    """Item 1a: the promised Acerbi-Szekely Z2 statistic, delivered as a
    per-(forecaster, rule) summary of the cell-level statistics stored in
    backtests.csv / baseline_backtests.csv (raw statistic, no bootstrap p —
    production stores as_z2(...)['stat'])."""
    bt = pd.read_csv(S4 / "backtests.csv")
    bl = pd.read_csv(S4 / "baseline_backtests.csv")
    check("z2 non-null TSFM count", int(bt.z2.notna().sum()) == 1425,
          f"{int(bt.z2.notna().sum())} != 1425")
    # v2.1.1 (review #11): HS-250 caliber — its single missing cell is
    # dgs30@1%, where 1bp-quantization ties (ES == VaR days) push the
    # valid-ES share under run_grid_extract's 0.99 guard; re-derived from
    # the per-day parquet, never pinned
    check("z2 hs250 cells == 95",
          int(bl[bl.forecaster == "hs250"].z2.notna().sum()) == 95)
    hp_path = S4 / "baselines" / "hs250_dgs30.parquet"
    if hp_path.exists():
        hp = pd.read_parquet(hp_path)
        hv, he = hp["v01"].to_numpy(), hp["e01"].to_numpy()
        ties = int((np.isfinite(he) & (he == hv)).sum())
        hgood = np.isfinite(he) & (he < hv) & (he < 0)
        check("z2 hs250 dgs30@1% guard math",
              ties == 70 and len(hp) == 2625 and hgood.mean() <= 0.99,
              f"ties {ties}, n {len(hp)}, good {hgood.mean():.4f}")
    else:
        # distribution copies do not carry the per-day baselines layer;
        # the 95-cell count above still verifies against the shipped CSV
        print("SKIP z2 hs250 dgs30@1% mechanism leg: baselines parquet "
              "absent (package copy); repo-side record: ties 70/2625")
    rows = []
    for f in TSFM:
        for er in ("e1", "e2", "e3"):
            d = bt[(bt.forecaster == f) & (bt.erule == er)].z2.dropna()
            rows.append((NAME[f], er.upper(), len(d), d.mean(), d.median(),
                         (d > 0).mean()))
    for f in BASE:
        d = bl[bl.forecaster == f].z2.dropna()
        if len(d):
            rows.append((NAME[f], "param", len(d), d.mean(), d.median(),
                         (d > 0).mean()))
    body = [
        r"\begin{table}[tbp]",
        r"\centering",
        r"\caption{Acerbi--Sz\'ekely $Z_2$ statistic, summarized over the",
        r"asset--tail cells per forecaster and extraction rule: cell count,",
        r"mean and median $Z_2$, and the share of cells with $Z_2>0$. $Z_2=0$",
        r"under a correct (VaR, ES) pair; $Z_2>0$ indicates realized tail",
        r"losses exceeding the predicted ES\@. The statistic is reported",
        r"descriptively, without a bootstrap $p$-value. E0 has no ES cell;",
        r"E3 counts below 96 reflect the dgs30 cells whose GPD ES is",
        r"genuinely undefined ($\xi\ge1$); CAViaR-SAV has no ES output. The",
        r"HS-250 count of 95 likewise reflects dgs30 ($\alpha=1\%$): 1bp",
        r"quantization ties the empirical ES to VaR on 70 of 2{,}625 days,",
        r"below the 99\% valid-ES-day guard.}",
        r"\label{tab:z2}",
        r"\footnotesize",
        r"\begin{tabular}{@{}llcccc@{}}",
        r"\toprule",
        r"forecaster & rule & cells & mean $Z_2$ & median $Z_2$ & share $>0$ \\",
        r"\midrule",
    ]
    prev = None
    for n, er, c, mn, md, sh in rows:
        if prev and n != prev and er == "param" and prev not in [NAME[b] for b in BASE]:
            body.append(r"\midrule")
        prev = n
        # v2.1.2 fix 7: negative means/medians render in math mode (proper
        # minus sign); with the current panel exactly three cells wrap
        neg = lambda s: f"${s}$" if s.startswith("-") else s
        body.append(f"{n} & {er} & {c} & {neg(f'{mn:.3f}')} & "
                    f"{neg(f'{md:.3f}')} & {sh*100:.0f}\\% \\\\")
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write_tex("tab_z2.tex", "\n".join(body))


def t_repairmcs():
    """Item 1g: repair-battery MCS membership at the registered dual levels,
    from repair_mcs_levels.csv (10% layer gated against repair_mcs.csv by
    run_mcs_levels)."""
    rm = pd.read_csv(S4 / "repair_mcs_levels.csv")
    body = [
        r"\begin{table}[tbp]",
        r"\centering",
        r"\caption{Repair-battery Model Confidence Sets at the two registered",
        r"levels: share of the 160 model--asset cells (5 heads $\times$ 32",
        r"assets) in which each arm survives the FZ0-loss MCS over the",
        r"seven-member set \{F1, F2, F3, F4, H, GARCH--EVT, FHS\}, matched",
        r"sample, by $\alpha$.}",
        r"\label{tab:repairmcs}",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{@{}lcccccc@{}}",
        r"\toprule",
        r" & \multicolumn{3}{c}{10\% level} & \multicolumn{3}{c}{25\% level} \\",
        r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}",
        r"arm & $\alpha=1\%$ & $2.5\%$ & $5\%$ & $\alpha=1\%$ & $2.5\%$ & $5\%$ \\",
        r"\midrule",
    ]
    for arm in ("F1", "F2", "F3", "F4", "H", "garch_evt", "fhs"):
        nm = {"garch_evt": "GARCH--EVT", "fhs": "FHS"}.get(arm, arm)
        cells = []
        for lv in (0.10, 0.25):
            for a in (0.01, 0.025, 0.05):
                d = rm[(rm.arm == arm) & (rm.alpha == a) & (rm.level == lv)]
                cells.append(f"{d.in_mcs.mean()*100:.0f}\\%")
        if arm == "garch_evt":
            body.append(r"\midrule")
        body.append(f"{nm} & " + " & ".join(cells) + r" \\")
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write_tex("tab_repairmcs.tex", "\n".join(body))


def t_matched_dates():
    """Item 1b: matched-date sensitivity on the five late-start assets —
    TSFM UC decisions on the delivered day sets vs the baseline-day-set
    intersection (matched_dates.csv; full-set side reproduction-gated
    against backtests.csv by run_matched_dates)."""
    md = pd.read_csv(S4 / "matched_dates.csv")
    flips = md[md.pass_full != md.pass_matched]
    body = [
        r"\begin{table}[tbp]",
        r"\centering",
        # v2.1 Phase 4 (visual round): this caption's last line lands with a
        # tight ~1.7pt ink gap to the toprule (others ~3.6pt; the rule read
        # as an underline at render). Explicit 2pt below-caption skip, set
        # BEFORE \caption (the caption macro consumes it). Typesetting only.
        r"\setlength{\belowcaptionskip}{2pt}",
        r"\caption{Matched-date sensitivity on the five late-start assets",
        r"(csi300, eth, xrp, btc, ltc), where the 1{,}000-day baseline",
        r"estimation window starts 459--488 trading days after the 512-day",
        r"TSFM context: MC-UC pass counts per head and rule over the",
        r"15 asset--tail cells, on the delivered TSFM day sets and on the",
        r"intersection with the baseline day sets (existing forecasts only).",
        r"`flips' counts cells whose UC decision changes; the flips are few",
        r"and not in one direction.}",
        r"\label{tab:matcheddates}",
        r"\footnotesize",
        r"\begin{tabular}{@{}llcccc@{}}",
        r"\toprule",
        r"head & rule & cells & pass (delivered) & pass (matched) & flips \\",
        r"\midrule",
    ]
    for f in TSFM:
        for er in ("e0", "e1", "e2", "e3"):
            d = md[(md.forecaster == f) & (md.erule == er)]
            if not len(d):
                continue
            body.append(
                f"{NAME[f]} & {er.upper()} & {len(d)} & "
                f"{int(d.pass_full.sum())} & {int(d.pass_matched.sum())} & "
                f"{int((d.pass_full != d.pass_matched).sum())} \\\\")
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write_tex("tab_matcheddates.tex", "\n".join(body))
    return len(md), int(flips.shape[0])


def t_cutoff():
    """Item 1l: per-head share of evaluation asset-days on or before the
    registered pretraining bound (cutoff_exposure.csv from run_p3_stats)."""
    ce = pd.read_csv(S4 / "cutoff_exposure.csv")
    body = [
        r"\begin{table}[tbp]",
        r"\centering",
        r"\caption{Pretraining-bound exposure of the evaluation sample: per",
        r"head, the registered calendar bound, total evaluation asset-days",
        r"over the 32 assets, and the share of those days on or before the",
        r"bound. Bounds follow two rules disclosed in",
        r"Section~\ref{sec:data}: Chronos-Bolt uses its pinned-revision date,",
        r"while Chronos-2, Moirai-2.0, and Lag-Llama use report-based",
        r"month-end bounds; TimesFM-2.5's bound is vendor-disclosed. Under a",
        r"unified revision-date rule, Chronos-2's bound would move to",
        r"2026-06-05 and its post-bound sample would shrink from 5{,}662 to",
        r"641 asset-days.}",
        r"\label{tab:cutoff}",
        r"\small",
        r"\begin{tabular}{@{}lccc@{}}",
        r"\toprule",
        r"head & bound & asset-days & share $\le$ bound \\",
        r"\midrule",
    ]
    for _, r in ce.iterrows():
        body.append(f"{NAME[r['model']]} & {r['bound']} & "
                    f"{int(r['days_total']):,} & "
                    f"{r['share_pre_bound']*100:.2f}\\% \\\\".replace(",", "{,}"))
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write_tex("tab_cutoff.tex", "\n".join(body))


def t_assets():
    """Item D-4: the 32-asset evaluation panel (group, sample span,
    transform, source), script-generated from data_manifest.yaml."""
    man = yaml.safe_load((ROOT / "data" / "data_manifest.yaml").read_text())
    keep = {k: v for k, v in man.items()
            if not v.get("quarantined") and v.get("group") != "vol_index"}
    check("asset table has 32 rows", len(keep) == 32, str(len(keep)))
    GN = {"equity_index": "equity index", "equity_single": "single stock",
          "fx": "FX", "crypto": "crypto", "commodity": "commodity",
          "rates": "rates"}
    body = [
        r"\begin{table}[tbp]",
        r"\centering",
        r"\caption{The 32-asset evaluation panel: series key, asset class,",
        r"raw sample span, return transform (log-return $\times100$ for",
        r"prices; daily basis-point first differences for Treasury yields),",
        r"and public source. Script-generated from the data manifest; the",
        r"two quarantined FX pairs and the two regime-dating volatility",
        r"indices are excluded (Section~\ref{sec:data}).}",
        r"\label{tab:assets}",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{@{}llllll@{}}",
        r"\toprule",
        r"key & class & start & end & transform & source \\",
        r"\midrule",
    ]
    order = ["equity_index", "equity_single", "fx", "crypto", "commodity",
             "rates"]
    prev_g = None
    for g in order:
        for k in sorted(x for x in keep if keep[x]["group"] == g):
            v = keep[k]
            if prev_g and g != prev_g:
                body.append(r"\addlinespace")
            prev_g = g
            tr = v.get("transform", "").replace("_", r"\_")
            body.append(f"\\texttt{{{k}}} & {GN[g]} & {v['start']} & "
                        f"{v['end']} & \\texttt{{{tr}}} & {v['source']} \\\\")
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write_tex("tab_assets.tex", "\n".join(body))


def t_ewma_fhs():
    """Phase-3 block 4: the EWMA/FHS controlled forecast-form contrast —
    identical lambda=0.94 sigma recursion (pinned by
    tests/test_baselines.py::test_ewma_fhs_share_sigma_path), differing only
    in tail form."""
    bl = pd.read_csv(S4 / "baseline_backtests.csv")
    esr = pd.read_csv(S4 / "esr_results.csv")
    vals = {}
    for f in ("ewma94", "fhs"):
        d1 = bl[(bl.forecaster == f) & (bl.alpha == 0.01)]
        # v2.1 Phase 3 (review #10 P1-4, option A): the ESR column is
        # filtered to alpha=1% like the UC and FZ0 columns — this table is
        # the alpha=1% controlled contrast; the v2.0 leg pooled all three
        # alpha levels under an "At alpha=1%" caption.
        es = esr[(esr.forecaster == f) & (esr.alpha == 0.01)]
        vals[f] = (int((d1.kupiec_p_mc > 0.05).sum()),
                   d1.fz0_mean.mean(),
                   (es.esr_p > 0.05).mean())
    check("ewma/fhs UC a1 counts", (vals["ewma94"][0], vals["fhs"][0]) == (2, 32),
          str((vals["ewma94"][0], vals["fhs"][0])))
    assert_val("ewma FZ0 a1", vals["ewma94"][1], 1.9604, tol=5e-4)
    assert_val("fhs FZ0 a1", vals["fhs"][1], 1.8140, tol=5e-4)
    body = [
        r"\begin{table}[tbp]",
        r"\centering",
        r"\caption{A controlled forecast-form contrast inside the econometric",
        r"battery: EWMA(0.94) and FHS share the same conditional-scale",
        r"recursion ($\lambda=0.94$, seeded at the window sample variance;",
        r"the identity is pinned by a unit test), and differ only in tail",
        r"form, a Gaussian quantile versus the filtered empirical tail. At",
        r"$\alpha=1\%$ the tail form alone moves the MC-UC pass count from",
        r"2/32 to 32/32; mean FZ0 and strict-ESR non-rejection move with",
        r"it. All three columns are computed at $\alpha=1\%$ over the 32",
        r"assets. Mean FZ0 is shown at four decimals because differences",
        r"within the FZ0 loss cluster are resolved at that precision.}",
        r"\label{tab:ewmafhs}",
        # v2.0 Phase-4 micro-round: \small width exceeds the named text block
        # by ~22pt; tabcolsep rung clears only at a cramped 2pt -> font rung.
        # v2.1 Phase 4: the P1-4 per-column alpha=1% headers widen the natural
        # width to textblock+34.7pt; colsep rung is arithmetically insufficient
        # (3 inner boundaries x 2 x 6pt = 36pt total colsep, ~1.7pt still over
        # at a cramped 0.5pt) -> ladder rung 3, downscale-only \resizebox (the
        # \ifdim guard keeps the wider blinded layout at natural size).
        r"\footnotesize",
        r"\resizebox{\ifdim\width>\textwidth\textwidth\else\width\fi}{!}{%",
        r"\begin{tabular}{@{}lccc@{}}",
        r"\toprule",
        r"forecaster & UC pass ($\alpha=1\%$) & mean FZ0 ($\alpha=1\%$) & ESR non-rej. ($\alpha=1\%$) \\",
        r"\midrule",
    ]
    for f, nm in (("ewma94", "EWMA(0.94), normal tail"),
                  ("fhs", "FHS, filtered empirical tail")):
        uc, fz, er = vals[f]
        body.append(f"{nm} & {uc}/32 & {fz:.4f} & {er*100:.1f}\\% \\\\")
    body += [r"\bottomrule", r"\end{tabular}}", r"\end{table}", ""]
    write_tex("tab_ewmafhs.tex", "\n".join(body))


# -------------------------------------------- T-CC/DQ appendix pass-rate table
def t_ccdq():
    """CC and DQ pass rates, main panel (32 assets), pooled over asset x alpha
    cells per (head, rule) — the companion to the UC table (signer hour-item
    2026-07-17). CC uses the MC-calibrated p; DQ has no MC null for its
    F-statistic in the battery and is reported at the asymptotic p (labeled)."""
    bt = pd.read_csv(S4 / "backtests.csv")
    bl = pd.read_csv(S4 / "baseline_backtests.csv")
    cc = lambda d: (d.cc_p_mc > 0.05).mean()
    dq = lambda d: (d.dq_p_asym > 0.05).mean()

    body = [
        r"\begin{table}[tbp]",
        r"\centering",
        r"\caption{Conditional-coverage (CC, Christoffersen; MC-calibrated) and",
        r"dynamic-quantile (DQ, four lags; asymptotic $p$) pass rates on the main",
        r"32-asset panel, pooled over asset $\times$ $\alpha$ cells per head and",
        r"extraction rule, at the 5\% test level. `param' = econometric",
        r"baselines' native parametric forecasts (structure as in",
        r"Table~\ref{tab:varaudit}); TimesFM-2.5's E0 dash follows the same",
        r"native-head restriction noted there. The DQ columns rest on the",
        r"asymptotic $\chi^2$ reference, which over-rejects at deep tails:",
        r"under the iid null at $n=2{,}639$, $\alpha=1\%$, the 5\%-level",
        r"asymptotic DQ test rejects 11.8\% of the time, so DQ levels are",
        r"comparable across forecasters but not sized at 5\%. The companion",
        r"unconditional-coverage table is Table~\ref{tab:varaudit}.}",
        # v2.0 Phase-3 S-1: asymptotic-size note (docs/v20_phase3_analyses.md
        # §14: 0.1178 at the production B=10,000, df-consistent hits-only DQ;
        # the review's reference value 0.0923 did not reproduce under any
        # nearby caliber — flagged in the Phase-3 report).
        r"\label{tab:ccdq}",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{3.5pt}",
        r"\begin{tabular}{@{}lcccccccccc@{}}",
        r"\toprule",
        r" & \multicolumn{5}{c}{CC pass (MC)} & \multicolumn{5}{c}{DQ pass (asym.)} \\",
        r"\cmidrule(lr){2-6}\cmidrule(lr){7-11}",
        r"forecaster & E0 & E1 & E2 & E3 & param & E0 & E1 & E2 & E3 & param \\",
        r"\midrule",
    ]
    for m in TSFM:
        cells = []
        for fn in (cc, dq):
            for e in ("e0", "e1", "e2", "e3"):
                d = bt[(bt.forecaster == m) & (bt.erule == e)]
                cells.append(f"{fn(d)*100:.0f}\\%" if len(d) else "---")
            cells.append("---")
        body.append(NAME[m] + " & " + " & ".join(cells) + r" \\")
    body.append(r"\midrule")
    for b in BASE:
        d = bl[bl.forecaster == b]
        cells = (["---", "---", "---", "---", f"{cc(d)*100:.0f}\\%"]
                 + ["---", "---", "---", "---", f"{dq(d)*100:.0f}\\%"])
        body.append(NAME[b] + " & " + " & ".join(cells) + r" \\")
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write_tex("tab_ccdq.tex", "\n".join(body))


# ------------------------------------------- v1.2 sensitivity tables (P0 6/7)
def t_v12():
    text = (ROOT / "docs/v12_sensitivity.md").read_text()
    tabs = md_tables(text)
    dec = next(t for t in tabs if "scale (F1-H)" in " ".join(t["headers"]))
    grid = next(t for t in tabs if "tol=1.00" in " ".join(t["headers"]))
    cnt = next(t for t in tabs if "pass count" in " ".join(t["headers"]))

    # asserts vs the frozen pack values (ep:191/ep:192 lag_llama terms) and
    # the published H coverage rates
    drow = {r[0]: r for r in dec["rows"]}
    check("v12 lag_llama scale term +0.152", drow["lag_llama"][3].startswith("+0.152"),
          drow["lag_llama"][3])
    check("v12 lag_llama loc term +0.009", drow["lag_llama"][4].startswith("+0.009"),
          drow["lag_llama"][4])
    crow = {r[0]: r for r in cnt["rows"]}
    for h, want in [("chronos_2", ("22/32", "69%")), ("moirai_2_0", ("23/32", "72%")),
                    ("lag_llama", ("26/32", "81%")), ("chronos_bolt", ("23/32", "72%")),
                    ("timesfm_2_5", ("23/32", "72%"))]:
        check(f"H pass count {h}", (crow[h][1], crow[h][2]) == want,
              f"{crow[h][1:]} != {want}")
    grow = {(r[0], r[1]): r for r in grid["rows"]}
    check("registered combo (10pp, 1.05, 2/3) 5/5", grow[("10", "2/3")][4] == "5",
          grow[("10", "2/3")][4])

    body = [
        r"\begin{table}[tbp]",
        r"\centering",
        r"\caption{Decomposition uncertainty at $\alpha=1\%$, E3, matched",
        r"sample: per-asset paired FZ0 differences, scale term (F1$-$H) and",
        r"location term (H$-$GE), with asset-class cluster block-bootstrap 95\%",
        r"confidence intervals (six classes resampled with replacement,",
        r"$B=2{,}000$). The count column reports assets on which the scale term",
        r"exceeds the location term. Scope: the evaluated one-step",
        r"decomposition.}",
        r"\label{tab:decompci}",
        r"\small",
        r"\begin{tabular}{@{}lccc@{}}",
        r"\toprule",
        r"head & scale$>$loc & scale (F1$-$H) [95\% CI] & loc (H$-$GE) [95\% CI] \\",
        r"\midrule"]
    def mcell(v):
        return "$" + v.replace(" [", "\\;[").replace(", ", ",\\, ") + "$"

    for h in HEAD_ORDER:
        r = drow[h]
        body.append(f"{NAME[h]} & {r[2]}/{r[1]} & {mcell(r[3])} & {mcell(r[4])} \\\\")
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write_tex("tab_decompci.tex", "\n".join(body))

    body = [
        r"\begin{table}[tbp]",
        r"\centering",
        r"\caption{Sensitivity of H's joint success to the registered",
        r"thresholds: number of heads (of 5) on which H passes the joint",
        r"criterion, over condition-(a) margin $\{5,10,15\}$\,pp $\times$",
        r"FZ0 tolerance $\{1.00,1.025,1.05,1.10\}$ $\times$ condition-(b)",
        r"fraction $\{1/2,2/3,3/4\}$ on the matched sample. The registered",
        r"combination (10\,pp, $1.05$, $2/3$; boxed) gives 5/5; all five heads",
        r"pass in 14 of 36 combinations; no head passes at tolerance $1.00$;",
        r"at a 5\,pp margin the condition-(a) threshold rises to $73.1\%$ and",
        r"four heads fall below it (Chronos-2 at $69\%$; Moirai-2.0,",
        r"Chronos-Bolt, and TimesFM-2.5 at $72\%$), so one of five heads",
        r"passes and the 5/5 headline is margin-sensitive.}",
        # v2.0 Phase-3: caption synced to the recomputed grid (moirai joined
        # the 5-pp failing set after its 3-pp move — impact §5); the stale
        # "three heads / two pass" caption contradicted sec10/appendix prose.
        r"\label{tab:sensgrid}",
        r"\small",
        r"\begin{tabular}{@{}llcccc@{}}",
        r"\toprule",
        r"margin & frac & tol $1.00$ & $1.025$ & $1.05$ & $1.10$ \\",
        r"\midrule"]
    for m in ("5", "10", "15"):
        for fr in ("1/2", "2/3", "3/4"):
            r = grow[(m, fr)]
            cells = list(r[2:6])
            if m == "10" and fr == "2/3":
                cells[2] = r"\fbox{" + cells[2] + r"}"
            body.append(f"{m}\\,pp & ${fr}$ & " + " & ".join(cells) + r" \\")
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write_tex("tab_sensgrid.tex", "\n".join(body))


if __name__ == "__main__":
    t_head_taxonomy()
    t_decoding()
    t_var_audit()
    t_var_audit_alpha()
    t_v15_robustness()
    t_esr()
    t_es_precision()
    t_taurec()
    t_prescription()
    t_mcs()
    t_z2()
    t_repairmcs()
    t_matched_dates()
    t_cutoff()
    t_assets()
    t_ewma_fhs()
    t_ccdq()
    t_v12()
    print("all table asserts passed")
    # G6 freshness stamp (v2.1.1, review #11): loud no-op inside package
    # copies (no .git); repo runs record generation-time input hashes
    from harness.freshness import stamp_safe
    stamp_safe("make_tables")
